### ISSUE TITLE
Feature: Notes for all scenes?

### ISSUE THREAD

**Issue by Fred-DTV** [exeldro/obs-scene-notes-dock#10]
Hello,

Thanks for creating this very useful plugin! It helps me a lot keeping track of problems that occur during live situations, so it is a lot easier to solve them afterwards.

Would it be possible to have an option, which lets the notes stay the same no matter which scene you're on?

**Comment by exeldro** [comment]
In that case it might be easier to use the Source Dock plugin to add a dock for a text source?

**Comment by Fred-DTV** [comment]
Smart! I will give that  a try :) Thanks
