### ISSUE TITLE
Missing compatibility new OBS API

### ISSUE THREAD

**Issue by fp-fxi** [exeldro/obs-scene-notes-dock#11]
The plugin makes uses of `obs_frontend_add_dock` that is now deprecated.

Should use one between `obs_frontend_add_dock_by_id` or `obs_frontend_add_custom_qdock` (the latter probably not since doesn't show the toggle in the Panel menu.

Refer to the PR https://github.com/obsproject/obs-studio/pull/7637

**Comment by exeldro** [comment]
this is fixed on master now
