### ISSUE TITLE
Please, provide a tag to allow packaging

### ISSUE THREAD

**Issue by eribertomota** [exeldro/obs-scene-notes-dock#2]
Dear @exeldro,

I am packaging this plugin for Debian and I need release points (tags). Please, consider #1 before release a new version.

Cheers,

Eriberto

**Comment by exeldro** [comment]
made and tagged the 0.0.2 release

**Comment by eribertomota** [comment]
Thanks! I think that a 0.0.3 tag will be needed after #1.

**Comment by eribertomota** [comment]
Hi @exeldro,

I just uploaded obs-scene-notes-dock 0.0.2 (plus a patch to add cmake minimum version and find_package) to Debian. To enter in Debian for the first time, the package needs an inspection by FTP Master team. This action is made between 1 and 90 days. After this, I will update to a new version, if you release it.

Thanks a lot for your work.

**Comment by eribertomota** [comment]
I forgot to say that I tested the plugin in OBS 26 and it worked fine.
